// <auto-generated />
namespace OrchidsWithLove_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddFlowersPhotos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFlowersPhotos));
        
        string IMigrationMetadata.Id
        {
            get { return "202307241114289_AddFlowersPhotos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
